/**
 * Expo Router paths for TransitOps mobile screens.
 * Dynamic segments use [id] to match file-based routing.
 */
export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  VEHICLES: '/vehicles',
  VEHICLES_NEW: '/vehicles/create',
  VEHICLE_DETAIL: '/vehicles/[id]',
  // Expo-compatible equivalent of [id]-edit.jsx → [id]/edit.jsx
  VEHICLE_EDIT: '/vehicles/[id]/edit',
  DRIVERS: '/drivers',
  DRIVERS_NEW: '/drivers/create',
  DRIVER_DETAIL: '/drivers/[id]',
  DRIVER_EDIT: '/drivers/[id]/edit',
  TRIPS: '/trips',
  TRIPS_NEW: '/trips/create',
  TRIP_DETAIL: '/trips/[id]',
  TRIP_EDIT: '/trips/[id]/edit',
  MAINTENANCE: '/maintenance',
  MAINTENANCE_NEW: '/maintenance/create',
  MAINTENANCE_DETAIL: '/maintenance/[id]',
  MAINTENANCE_EDIT: '/maintenance/[id]/edit',
  FUEL: '/fuel',
  FUEL_NEW: '/fuel/create',
  FUEL_DETAIL: '/fuel/[id]',
  FUEL_EDIT: '/fuel/[id]/edit',
  EXPENSES: '/expenses',
  EXPENSES_NEW: '/expenses/create',
  EXPENSE_DETAIL: '/expenses/[id]',
  EXPENSE_EDIT: '/expenses/[id]/edit',
  REPORTS: '/reports',
  ADMIN_USERS: '/admin/users',
  ADMIN_USERS_NEW: '/admin/users/create',
  ADMIN_USER_DETAIL: '/admin/users/[id]',
  ADMIN_USER_EDIT: '/admin/users/[id]/edit',
  ADMIN_ROLES: '/admin/roles',
  ADMIN_ROLE_DETAIL: '/admin/roles/[id]',
  ADMIN_ROLE_PERMISSIONS: '/admin/roles/[id]/permissions',
  PROFILE: '/profile',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '+not-found',
  INDEX: '/',
}
