import {
  DRIVER_STATUS,
  MAINTENANCE_STATUS,
  USER_STATUS,
  VEHICLE_STATUS,
} from './statuses'

export const VEHICLE_FORM_STATUSES = [
  VEHICLE_STATUS.AVAILABLE,
  VEHICLE_STATUS.RETIRED,
]

export const DRIVER_FORM_STATUSES = [
  DRIVER_STATUS.AVAILABLE,
  DRIVER_STATUS.OFF_DUTY,
  DRIVER_STATUS.SUSPENDED,
]

/** Backend creates maintenance as SCHEDULED; start moves it to IN_PROGRESS. */
export const MAINTENANCE_CREATE_STATUSES = [MAINTENANCE_STATUS.SCHEDULED]

export const USER_FORM_STATUSES = [USER_STATUS.ACTIVE, USER_STATUS.INACTIVE]
