export const QUERY_KEYS = {
  AUTH_ME: ['auth', 'me'],
  DASHBOARD_SUMMARY: ['dashboard', 'summary'],
  VEHICLES: ['vehicles'],
  VEHICLE: (id) => ['vehicles', id],
  DRIVERS: ['drivers'],
  DRIVER: (id) => ['drivers', id],
  TRIPS: ['trips'],
  TRIP: (id) => ['trips', id],
  MAINTENANCE: ['maintenance'],
  MAINTENANCE_ITEM: (id) => ['maintenance', id],
  FUEL: ['fuel'],
  FUEL_ITEM: (id) => ['fuel', id],
  EXPENSES: ['expenses'],
  EXPENSE: (id) => ['expenses', id],
  REPORTS: ['reports'],
  USERS: ['users'],
  USER: (id) => ['users', id],
  ROLES: ['roles'],
  ROLE: (id) => ['roles', id],
}
