import { ROLES } from '@/constants/roles'
import { PERMISSIONS } from '@/constants/permissions'

/**
 * Role + permission gated dashboard visibility.
 * Mirrors the web dashboardRoleConfig for consistent role-aware KPIs.
 */
export const DASHBOARD_SECTION_KEYS = {
  KPI_GRID: 'kpiGrid',
  CHARTS: 'charts',
  RECENT_TRIPS: 'recentTrips',
  EXPIRING_LICENCES: 'expiringLicences',
  VEHICLES_IN_MAINTENANCE: 'vehiclesInMaintenance',
  SAFETY_FOCUS: 'safetyFocus',
  FINANCIAL_FOCUS: 'financialFocus',
  PENDING_USERS: 'pendingUsers',
}

export const DASHBOARD_KPI_KEYS = {
  ACTIVE_VEHICLES: 'activeVehicles',
  AVAILABLE_VEHICLES: 'availableVehicles',
  VEHICLES_ON_TRIP: 'vehiclesOnTrip',
  VEHICLES_IN_MAINTENANCE: 'vehiclesInMaintenance',
  ACTIVE_TRIPS: 'activeTrips',
  PENDING_TRIPS: 'pendingTrips',
  DRIVERS_ON_DUTY: 'driversOnDuty',
  AVAILABLE_DRIVERS: 'availableDrivers',
  FLEET_UTILIZATION: 'fleetUtilization',
  TOTAL_OPERATIONAL_COST: 'totalOperationalCost',
  FUEL_COST: 'fuelCost',
  MAINTENANCE_COST: 'maintenanceCost',
  EXPENSES: 'expenses',
  REVENUE: 'revenue',
  VEHICLE_ROI: 'vehicleRoi',
  FUEL_EFFICIENCY: 'fuelEfficiency',
  EXPIRED_LICENCES: 'expiredLicences',
  EXPIRING_LICENCES: 'expiringLicences',
  SUSPENDED_DRIVERS: 'suspendedDrivers',
  AVERAGE_SAFETY_SCORE: 'averageSafetyScore',
}

const ALL_OPERATIONAL_KPIS = [
  DASHBOARD_KPI_KEYS.ACTIVE_VEHICLES,
  DASHBOARD_KPI_KEYS.AVAILABLE_VEHICLES,
  DASHBOARD_KPI_KEYS.VEHICLES_ON_TRIP,
  DASHBOARD_KPI_KEYS.VEHICLES_IN_MAINTENANCE,
  DASHBOARD_KPI_KEYS.ACTIVE_TRIPS,
  DASHBOARD_KPI_KEYS.PENDING_TRIPS,
  DASHBOARD_KPI_KEYS.DRIVERS_ON_DUTY,
  DASHBOARD_KPI_KEYS.AVAILABLE_DRIVERS,
  DASHBOARD_KPI_KEYS.FLEET_UTILIZATION,
  DASHBOARD_KPI_KEYS.TOTAL_OPERATIONAL_COST,
]

const FLEET_KPIS = [
  DASHBOARD_KPI_KEYS.ACTIVE_VEHICLES,
  DASHBOARD_KPI_KEYS.AVAILABLE_VEHICLES,
  DASHBOARD_KPI_KEYS.VEHICLES_ON_TRIP,
  DASHBOARD_KPI_KEYS.VEHICLES_IN_MAINTENANCE,
  DASHBOARD_KPI_KEYS.FLEET_UTILIZATION,
]

const DISPATCH_KPIS = [
  DASHBOARD_KPI_KEYS.ACTIVE_TRIPS,
  DASHBOARD_KPI_KEYS.PENDING_TRIPS,
  DASHBOARD_KPI_KEYS.AVAILABLE_VEHICLES,
  DASHBOARD_KPI_KEYS.AVAILABLE_DRIVERS,
]

const SAFETY_KPIS = [
  DASHBOARD_KPI_KEYS.DRIVERS_ON_DUTY,
  DASHBOARD_KPI_KEYS.AVAILABLE_DRIVERS,
  DASHBOARD_KPI_KEYS.EXPIRED_LICENCES,
  DASHBOARD_KPI_KEYS.EXPIRING_LICENCES,
  DASHBOARD_KPI_KEYS.SUSPENDED_DRIVERS,
  DASHBOARD_KPI_KEYS.AVERAGE_SAFETY_SCORE,
]

const FINANCIAL_KPIS = [
  DASHBOARD_KPI_KEYS.FUEL_COST,
  DASHBOARD_KPI_KEYS.MAINTENANCE_COST,
  DASHBOARD_KPI_KEYS.EXPENSES,
  DASHBOARD_KPI_KEYS.REVENUE,
  DASHBOARD_KPI_KEYS.VEHICLE_ROI,
  DASHBOARD_KPI_KEYS.FUEL_EFFICIENCY,
  DASHBOARD_KPI_KEYS.TOTAL_OPERATIONAL_COST,
]

const ROLE_DASHBOARD_CONFIG = {
  [ROLES.SUPER_ADMIN]: {
    kpis: [
      ...ALL_OPERATIONAL_KPIS,
      ...FINANCIAL_KPIS.filter((key) => !ALL_OPERATIONAL_KPIS.includes(key)),
    ],
    sections: [
      DASHBOARD_SECTION_KEYS.KPI_GRID,
      DASHBOARD_SECTION_KEYS.CHARTS,
      DASHBOARD_SECTION_KEYS.PENDING_USERS,
      DASHBOARD_SECTION_KEYS.RECENT_TRIPS,
      DASHBOARD_SECTION_KEYS.EXPIRING_LICENCES,
      DASHBOARD_SECTION_KEYS.VEHICLES_IN_MAINTENANCE,
      DASHBOARD_SECTION_KEYS.FINANCIAL_FOCUS,
    ],
    charts: [
      'vehicleStatusDistribution',
      'tripStatusDistribution',
      'monthlyFuelCost',
      'monthlyMaintenanceCost',
      'expenseBreakdown',
    ],
  },
  [ROLES.FLEET_MANAGER]: {
    kpis: FLEET_KPIS,
    sections: [
      DASHBOARD_SECTION_KEYS.KPI_GRID,
      DASHBOARD_SECTION_KEYS.CHARTS,
      DASHBOARD_SECTION_KEYS.VEHICLES_IN_MAINTENANCE,
      DASHBOARD_SECTION_KEYS.RECENT_TRIPS,
    ],
    charts: [
      'vehicleStatusDistribution',
      'monthlyMaintenanceCost',
      'tripStatusDistribution',
    ],
  },
  [ROLES.DISPATCHER]: {
    kpis: DISPATCH_KPIS,
    sections: [
      DASHBOARD_SECTION_KEYS.KPI_GRID,
      DASHBOARD_SECTION_KEYS.CHARTS,
      DASHBOARD_SECTION_KEYS.RECENT_TRIPS,
    ],
    charts: ['tripStatusDistribution', 'vehicleStatusDistribution'],
  },
  [ROLES.SAFETY_OFFICER]: {
    kpis: SAFETY_KPIS,
    sections: [
      DASHBOARD_SECTION_KEYS.KPI_GRID,
      DASHBOARD_SECTION_KEYS.SAFETY_FOCUS,
      DASHBOARD_SECTION_KEYS.EXPIRING_LICENCES,
    ],
    charts: [],
  },
  [ROLES.FINANCIAL_ANALYST]: {
    kpis: FINANCIAL_KPIS,
    sections: [
      DASHBOARD_SECTION_KEYS.KPI_GRID,
      DASHBOARD_SECTION_KEYS.CHARTS,
      DASHBOARD_SECTION_KEYS.FINANCIAL_FOCUS,
    ],
    charts: [
      'monthlyFuelCost',
      'monthlyMaintenanceCost',
      'expenseBreakdown',
    ],
  },
}

const SECTION_PERMISSIONS = {
  [DASHBOARD_SECTION_KEYS.KPI_GRID]: [PERMISSIONS.DASHBOARD_VIEW],
  [DASHBOARD_SECTION_KEYS.CHARTS]: [PERMISSIONS.DASHBOARD_VIEW],
  [DASHBOARD_SECTION_KEYS.RECENT_TRIPS]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TRIPS_VIEW,
  ],
  [DASHBOARD_SECTION_KEYS.EXPIRING_LICENCES]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DRIVERS_VIEW,
  ],
  [DASHBOARD_SECTION_KEYS.VEHICLES_IN_MAINTENANCE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
  ],
  [DASHBOARD_SECTION_KEYS.SAFETY_FOCUS]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.DRIVERS_VIEW,
  ],
  [DASHBOARD_SECTION_KEYS.FINANCIAL_FOCUS]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [DASHBOARD_SECTION_KEYS.PENDING_USERS]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.USERS_VIEW,
  ],
}

const KPI_PERMISSIONS = {
  [DASHBOARD_KPI_KEYS.ACTIVE_VEHICLES]: [PERMISSIONS.VEHICLES_VIEW],
  [DASHBOARD_KPI_KEYS.AVAILABLE_VEHICLES]: [PERMISSIONS.VEHICLES_VIEW],
  [DASHBOARD_KPI_KEYS.VEHICLES_ON_TRIP]: [PERMISSIONS.VEHICLES_VIEW],
  [DASHBOARD_KPI_KEYS.VEHICLES_IN_MAINTENANCE]: [
    PERMISSIONS.VEHICLES_VIEW,
    PERMISSIONS.MAINTENANCE_VIEW,
  ],
  [DASHBOARD_KPI_KEYS.ACTIVE_TRIPS]: [PERMISSIONS.TRIPS_VIEW],
  [DASHBOARD_KPI_KEYS.PENDING_TRIPS]: [PERMISSIONS.TRIPS_VIEW],
  [DASHBOARD_KPI_KEYS.DRIVERS_ON_DUTY]: [PERMISSIONS.DRIVERS_VIEW],
  [DASHBOARD_KPI_KEYS.AVAILABLE_DRIVERS]: [PERMISSIONS.DRIVERS_VIEW],
  [DASHBOARD_KPI_KEYS.FLEET_UTILIZATION]: [PERMISSIONS.VEHICLES_VIEW],
  [DASHBOARD_KPI_KEYS.TOTAL_OPERATIONAL_COST]: [
    PERMISSIONS.FUEL_VIEW,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [DASHBOARD_KPI_KEYS.FUEL_COST]: [PERMISSIONS.FUEL_VIEW],
  [DASHBOARD_KPI_KEYS.MAINTENANCE_COST]: [PERMISSIONS.MAINTENANCE_VIEW],
  [DASHBOARD_KPI_KEYS.EXPENSES]: [PERMISSIONS.EXPENSES_VIEW],
  [DASHBOARD_KPI_KEYS.REVENUE]: [PERMISSIONS.REPORTS_VIEW],
  [DASHBOARD_KPI_KEYS.VEHICLE_ROI]: [PERMISSIONS.REPORTS_VIEW],
  [DASHBOARD_KPI_KEYS.FUEL_EFFICIENCY]: [PERMISSIONS.FUEL_VIEW],
  [DASHBOARD_KPI_KEYS.EXPIRED_LICENCES]: [PERMISSIONS.DRIVERS_VIEW],
  [DASHBOARD_KPI_KEYS.EXPIRING_LICENCES]: [PERMISSIONS.DRIVERS_VIEW],
  [DASHBOARD_KPI_KEYS.SUSPENDED_DRIVERS]: [PERMISSIONS.DRIVERS_VIEW],
  [DASHBOARD_KPI_KEYS.AVERAGE_SAFETY_SCORE]: [PERMISSIONS.DRIVERS_VIEW],
}

function hasAllPermissions(hasPermission, permissions = []) {
  if (!permissions.length) return true
  return permissions.every((permission) => hasPermission(permission))
}

function hasAnyPermission(hasPermission, permissions = []) {
  if (!permissions.length) return true
  return permissions.some((permission) => hasPermission(permission))
}

export function getDashboardConfigForRole(role) {
  return ROLE_DASHBOARD_CONFIG[role] || ROLE_DASHBOARD_CONFIG[ROLES.DISPATCHER]
}

export function canShowDashboardSection(sectionKey, { role, hasPermission }) {
  const config = getDashboardConfigForRole(role)
  if (!config.sections.includes(sectionKey)) return false
  if (!hasPermission(PERMISSIONS.DASHBOARD_VIEW)) return false
  return hasAllPermissions(hasPermission, SECTION_PERMISSIONS[sectionKey])
}

export function getVisibleDashboardKpis(role, hasPermission) {
  const config = getDashboardConfigForRole(role)
  return config.kpis.filter((kpiKey) => {
    const required = KPI_PERMISSIONS[kpiKey] || []
    if (
      kpiKey === DASHBOARD_KPI_KEYS.TOTAL_OPERATIONAL_COST ||
      kpiKey === DASHBOARD_KPI_KEYS.VEHICLES_IN_MAINTENANCE
    ) {
      return hasAnyPermission(hasPermission, required)
    }
    return hasAllPermissions(hasPermission, required)
  })
}

export function getVisibleDashboardCharts(role, hasPermission) {
  if (!hasPermission(PERMISSIONS.DASHBOARD_VIEW)) return []
  const config = getDashboardConfigForRole(role)
  return config.charts || []
}
