const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};

const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  FLEET_MANAGER: "FLEET_MANAGER",
  DISPATCHER: "DISPATCHER",
  SAFETY_OFFICER: "SAFETY_OFFICER",
  FINANCIAL_ANALYST: "FINANCIAL_ANALYST",
};

const ROLE_LABELS = {
  SUPER_ADMIN: "Super Admin",
  FLEET_MANAGER: "Fleet Manager",
  DISPATCHER: "Dispatcher",
  SAFETY_OFFICER: "Safety Officer",
  FINANCIAL_ANALYST: "Financial Analyst",
};

const PERMISSION_KEYS = {
  DASHBOARD_VIEW: "dashboard.view",
  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_EDIT: "users.edit",
  USERS_CHANGE_STATUS: "users.change_status",
  ROLES_VIEW: "roles.view",
  ROLES_EDIT: "roles.edit",
  ROLES_PERMISSIONS: "roles.permissions",
  VEHICLES_VIEW: "vehicles.view",
  VEHICLES_CREATE: "vehicles.create",
  VEHICLES_EDIT: "vehicles.edit",
  VEHICLES_RETIRE: "vehicles.retire",
  DRIVERS_VIEW: "drivers.view",
  DRIVERS_CREATE: "drivers.create",
  DRIVERS_EDIT: "drivers.edit",
  DRIVERS_CHANGE_STATUS: "drivers.change_status",
  DRIVERS_SUSPEND: "drivers.suspend",
  TRIPS_VIEW: "trips.view",
  TRIPS_CREATE: "trips.create",
  TRIPS_EDIT_DRAFT: "trips.edit_draft",
  TRIPS_DISPATCH: "trips.dispatch",
  TRIPS_COMPLETE: "trips.complete",
  TRIPS_CANCEL: "trips.cancel",
  MAINTENANCE_VIEW: "maintenance.view",
  MAINTENANCE_CREATE: "maintenance.create",
  MAINTENANCE_EDIT: "maintenance.edit",
  MAINTENANCE_COMPLETE: "maintenance.complete",
  MAINTENANCE_CANCEL: "maintenance.cancel",
  FUEL_VIEW: "fuel.view",
  FUEL_CREATE: "fuel.create",
  FUEL_EDIT: "fuel.edit",
  FUEL_DELETE: "fuel.delete",
  EXPENSES_VIEW: "expenses.view",
  EXPENSES_CREATE: "expenses.create",
  EXPENSES_EDIT: "expenses.edit",
  EXPENSES_DELETE: "expenses.delete",
  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",
};

module.exports = {
  HTTP_STATUS,
  ROLES,
  ROLE_LABELS,
  PERMISSION_KEYS,
};
